export class Actions {
    constructor(response: any);
    getResponseValueFromKey(json: any, key: any): any;
    deleted_fields: any;
    verify_recipient: any;
    is_bulk: any;
    action_id: any;
    action_type: any;
    private_notes: any;
    recipient_email: any;
    signing_order: any;
    recipient_name: any;
    fields: fields.Fields;
    recipient_countrycode: any;
    recipient_countrycode_iso: any;
    recipient_phonenumber: any;
    language: any;
    verification_type: any;
    verification_code: any;
    delivery_mode: any;
    role: any;
    is_embedded: any;
    getVerifyRecipient(): any;
    getIsBulk(): any;
    getActionId(): any;
    getActionType(): any;
    getPrivateNotes(): any;
    getRecipientEmail(): any;
    getActionEmail(): any;
    getSigningOrder(): any;
    getRecipientName(): any;
    getActionName(): any;
    getFields(): fields.Fields;
    getDeletedFields(): any;
    getRecipientCountrycode(): any;
    getRecipientCountrycodeISO(): any;
    getRecipientPhonenumber(): any;
    getLanguage(): any;
    getVerificationType(): any;
    getVerificationCode(): any;
    getRole(): any;
    getIsEmbedded(): any;
    getDeliveryMode(): any;
    setVerifyRecipient(verify_recipient: any): void;
    setIsBulk(is_bulk: any): void;
    setActionId(action_id: any): void;
    setActionType(action_type: any): void;
    setPrivateNotes(private_notes: any): void;
    setRecipientEmail(recipient_email: any): void;
    setActionEmail(recipient_email: any): void;
    setSigningOrder(signing_order: any): void;
    setRecipientName(recipient_name: any): void;
    setActionName(recipient_name: any): void;
    setFields(fields: any): void;
    setDeletedFields(deleted_fields: any): void;
    setRecipientCountrycode(recipient_countrycode: any): void;
    setRecipientCountrycodeISO(recipient_countrycode_iso: any): void;
    setRecipientPhonenumber(recipient_phonenumber: any): void;
    setLanguage(language: any): void;
    setVerificationType(verification_type: any): void;
    setVerificationCode(verification_code: any): void;
    setRole(role: any): void;
    setIsEmbedded(is_embedded: any): void;
    setDeliveryMode(delivery_mode: any): void;
    constructJson(): {};
}
import fields = require("zsign-nodejs-sdk/src/api/Fields");
//# sourceMappingURL=Action.d.ts.map