export class FieldSettersAndGetters {
    getFieldId(): any;
    getX_coord(): any;
    getFieldTypeId(): any;
    getFieldTypeName(): any;
    getAbsHeight(): any;
    getFieldCategory(): any;
    getFieldLabel(): any;
    getIsMandatory(): any;
    getPageNum(): any;
    getDocumentId(): any;
    getFieldName(): any;
    getY_value(): any;
    getAbsWidth(): any;
    getActionId(): any;
    getWidth(): any;
    getY_coord(): any;
    getDescriptionTooltip(): any;
    getX_value(): any;
    getHeight(): any;
    getIsReadOnly(): any;
    getDateFormat(): any;
    getDefaultValue(): any;
    getTextProperty(): any;
    getNameFormat(): any;
    setFieldId(field_id: any): void;
    field_id: any;
    setX_coord(x_coord: any): void;
    x_coord: any;
    setFieldTypeId(field_type_id: any): void;
    field_type_id: any;
    setFieldTypeName(field_type_name: any): void;
    field_type_name: any;
    setAbsHeight(abs_height: any): void;
    abs_height: any;
    setFieldCategory(field_category: any): void;
    field_category: any;
    setFieldLabel(field_label: any): void;
    field_label: any;
    setIsMandatory(is_mandatory: any): void;
    is_mandatory: any;
    setPageNum(page_no: any): void;
    page_no: any;
    setDocumentId(document_id: any): void;
    document_id: any;
    setFieldName(field_name: any): void;
    field_name: any;
    setY_value(y_value: any): void;
    y_value: any;
    setAbsWidth(abs_width: any): void;
    abs_width: any;
    setActionId(action_id: any): void;
    action_id: any;
    setWidth(width: any): void;
    width: any;
    setY_coord(y_coord: any): void;
    y_coord: any;
    setDescriptionTooltip(description_tooltip: any): void;
    description_tooltip: any;
    setX_value(x_value: any): void;
    x_value: any;
    setHeight(height: any): void;
    height: any;
    setIsReadOnly(is_read_only: any): void;
    is_read_only: any;
    setDefaultValue(default_value: any): void;
    default_value: any;
    setTextProperty(text_property: any): void;
    text_property: any;
    setDateFormat(date_format: any): void;
    date_format: any;
    setNameFormat(name_format: any): void;
    name_format: any;
}
//# sourceMappingURL=FieldSettersAndGetters.d.ts.map