export class RequestObject {
    constructor(response: any);
    getResponseValueFromKey(json: any, key: any): any;
    document_ids: any[];
    actions: any[];
    deleted_actions: any;
    request_id: any;
    request_status: any;
    request_name: any;
    email_reminders: any;
    notes: any;
    reminder_period: any;
    expiration_days: any;
    is_sequential: any;
    description: any;
    validity: any;
    request_type_id: any;
    folder_id: any;
    self_sign: any;
    bulk_actions: any;
    is_bulk: any;
    bulk_request_id: any;
    custom_data: any;
    owner_email: any;
    owner_first_name: any;
    owner_last_name: any;
    owner_id: any;
    created_time: any;
    modified_time: any;
    getRequestId(): any;
    getRequestStatus(): any;
    getRequestName(): any;
    getSelfSign(): any;
    getAutomaiticReminders(): any;
    getDocumentIds(): any[];
    getNotes(): any;
    getReminderPeriod(): any;
    getRedirectPages(): any;
    getExpirationDays(): any;
    getSequentialSigning(): any;
    getDescription(): any;
    getValidity(): any;
    getRequestTypeId(): any;
    getActions(): any[];
    getDeleted_actions(): any;
    getPageNum(): any;
    getExpirationAlertPeriod(): any;
    getBulkActions(): any;
    getIsBulk(): any;
    getCustomData(): any;
    getOwnerEmail(): any;
    getOwnerFirstName(): any;
    getOwnerId(): any;
    getOwnerLastName(): any;
    getCreatedTime(): any;
    getModifiedTime(): any;
    getFolderId(): any;
    setRequestId(request_id: any): void;
    setRequestName(request_name: any): void;
    setSelfSign(self_sign: any): void;
    setAutomaticReminders(email_reminders: any): void;
    setDocumentIds(document_ids: any): void;
    setNotes(notes: any): void;
    setReminderPeriod(reminder_period: any): void;
    setExpirationDays(expiration_days: any): void;
    setSequentialSigning(is_sequential: any): void;
    setDescription(description: any): void;
    setValidity(validity: any): void;
    setRequestTypeId(request_type_id: any): void;
    setRedirectPages(redirect_pages: any): void;
    redirect_pages: any;
    addAction(action: any): void;
    setActions(actions: any): void;
    setDeletedActions(deleted_actions: any): void;
    setPageNum(page_num: any): void;
    page_num: any;
    setExpirationAlertPeriod(): void;
    expiration_alert_period: any;
    setBulkActions(bulk_actions: any): void;
    setIsBulk(is_bulk: any): void;
    setCustomData(custom_data: any): void;
    setFolderId(folder_id: any): void;
    constructJson(): {};
}
//# sourceMappingURL=RequestObject.d.ts.map