export class TemplateObject {
    constructor(response?: any);
    getResponseValueFromKey(json: any, key: any): any;
    document_ids: any[];
    actions: any[];
    created_time: any;
    modified_time: any;
    template_id: any;
    template_name: any;
    email_reminders: any;
    notes: any;
    reminder_period: any;
    expiration_days: any;
    is_sequential: any;
    description: any;
    validity: any;
    request_type_id: any;
    request_type_name: any;
    folder_id: any;
    self_sign: any;
    bulk_actions: any;
    is_bulk: any;
    bulk_template_id: any;
    custom_data: any;
    owner_email: any;
    owner_first_name: any;
    owner_last_name: any;
    owner_id: any;
    field_text_data: {};
    field_boolean_data: {};
    field_date_data: {};
    field_radio_data: {};
    document_fields: any[];
    getTemplateId(): any;
    getTemplateName(): any;
    getSelfSign(): any;
    getAutomaticReminders(): any;
    getDocumentIds(): any[];
    getNotes(): any;
    getReminderPeriod(): any;
    getExpirationDays(): any;
    getSequentialSigning(): any;
    getDescription(): any;
    getValidity(): any;
    getRequestTypeId(): any;
    getActions(): any[];
    getDeleted_actions(): any;
    getPageNum(): any;
    getExpirationAlertPeriod(): any;
    getBulkActions(): any;
    getIsBulk(): any;
    getCustomData(): any;
    getCreatedTime(): any;
    getModifiedTime(): any;
    getDocumentFields(): any[];
    getRequestName(): any;
    getOwnerEmail(): any;
    getOwnerFirstName(): any;
    getOwnerId(): any;
    getOwnerLastName(): any;
    setTemplateId(template_id: any): void;
    setTemplateName(template_name: any): void;
    setSelfSign(self_sign: any): void;
    setAutomaticReminders(email_reminders: any): void;
    setEmailReminders(email_reminders: any): void;
    setDocumentIds(document_ids: any): void;
    setNotes(notes: any): void;
    setReminderPeriod(reminder_period: any): void;
    setExpirationDays(expiration_days: any): void;
    setSequentialSigning(is_sequential: any): void;
    setDescription(description: any): void;
    setValidity(validity: any): void;
    setRequestTypeId(request_type_id: any): void;
    addAction(action: any): void;
    setActions(actions: any): void;
    setDeletedActions(deleted_actions: any): void;
    setPageNum(page_num: any): void;
    page_num: any;
    setExpirationAlertPeriod(): void;
    expiration_alert_period: any;
    setBulkActions(bulk_actions: any): void;
    setIsBulk(is_bulk: any): void;
    setCustomData(custom_data: any): void;
    setCreatedTime(created_time: any): void;
    setModifiedTime(modified_time: any): void;
    setRequestName(requestName: any): void;
    request_name: any;
    getPrefillTextField(field_label?: any): any;
    getPrefillBooleanField(field_label?: any): any;
    getPrefillDateField(field_label?: any): any;
    getFieldRadioData(): {};
    setPrefillTextField(label: any, value: any): void;
    setPrefillBooleanField(label: any, value: any): void;
    setPrefillDateField(label: any, value: any): void;
    setPrefillRadioField(label: any, value: any): void;
    getActionByRole(role: any): never;
    constructJson(): {};
    constructJsonForSubmit(): {
        field_data: {
            field_text_data: {};
            field_boolean_data: {};
            field_date_data: {};
            field_radio_data: {};
        };
        actions: any[];
        notes: any;
        request_name: any;
        custom_data: any;
        is_bulk: any;
    };
}
//# sourceMappingURL=TemplateObject.d.ts.map